os:
  - linux

language: python

env:
  matrix:
    - python=3.5  CONDA_PY=35  
    - python=3.6  CONDA_PY=36

  global:
    - secure: "L2zrE9iFoi4MRXxhif1WtevwymjWY+/uBCrz3Q8WK89Kq95UhAmkt4w/Dnrkuzd7KpKoyCui5XynYH5SSMJ+Qra7AdWhNILm1T625UISWJJWXPjrJr6LOBRWdhDsR3P3ZCcyuDONv7chisYlEKvZOW60EO9TUfAqhj6LhMZPb19VvsSbVyXI/SjljgpaN5RRTboJ1Fg2iCHTVWJpVS6Ve+w3XSR7r4N1iXuv8hpbmq3ddkF0aUT/aFv6Zod6qRlRuQAyaP9dpa0wxkNLHnkTuycDvRIgAzaBMoF4to0v5HKLwZiJTsp3hm8ONMQ6NiUIqRdcrzaRxD09c8I4ADgo3NZJf1I0zPmOmfEusgLzdy3/ASs4EXI97Jlr+YF57N9SlsboQrxlRYnDQwwW+DjeOyZG4lqFPGg8bfPU+QRcea4kAegq9zjfucX36T8zLNZJqxsTBoSdXo/uHXxn8dv605e565EDNPtRYpCamNh0JlAbVQt7khPAWXFPId4ZpxCpdPxntpCmOBpAb5bO6n5ifqkPmPbMXznNQEaMk0lsbH2c6zuFovHEJ4cPM3tyrZRU+BKWMxCpw1sKD1LaDf0eZpHYPI+3FK5cqrlZzva2dkea/v+Iaya0+6P2ykRgYRyiP1+zLpL8Tl3pqxUY9eEMkw26JoU+610aRcUh4C9dM2g="
    - secure: "YJgSGFNbJCR4ALGV7XwjOlbaV//uYZGg8ARCiPeAnaTxF4Y6fP4k3OT+s0tyUTubJGbfltn3L6OEuekyHBS5tseuNuvcihubf/6TSY9ssolKLZKaEHBkHtKKCYdIiSxDvGq6AxqpiHx0ZYXR+vy3xPDVi4kldDYzfcwhMpf0VlI5u47Df5x8RaO37RfEIayfOHbLUtvJzWrbR+7yHlew9AaWorOthzgNNMxBYYqnqVKdztm8YXI/X0H6rcWcHS0TaeWWr1d3oewt9Opnm6LJnYyg6+kqiA23PEicMOf/iTb7K0pgkB3edDhM88GXBa5zSn0MqVW1bpcubWdHuqScF5bdRdZ+C03QdKxHRWCIjPTDFPf2Zwl0w/T8HNNmV9Lxd7dQVh1eaaSI6F23rNU7CiYgpSqFT+Ce1HRf9yifot2eOurb+YOf8XqzkN0/sioloGvA0BV4ToL73wxbGwqDEWN9n+iuxvUyMy48VmReeDr0GVDr/YGVCOfCCEkoGQ25IpBpHmVBlfA/0fGDfBInj3mi0pwI06XntKdZ+/x5WdVHRrH4RCutVhA9mPX/5l3NKV7LgcXGf2pi2tTppoL7olJBaJlwx1idF9YWQwmBFPTP1pIESRuujkmXPQG156bUVoFueQ9WjaXKSXKeZrsP4LXHTEUZVR1Peae/4btTJfs="    


before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod 755 miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n ingeotec python=$python
  - source activate ingeotec
  - conda install --yes pip
  - pip install coverage
  - pip install coveralls
  - conda config --append channels ingeotec
  - conda install --yes numpy scipy scikit-learn gensim nose
  - python setup.py build_ext --inplace
  
script:
  - which python
  - python --version
  - which coverage
  - if [ $python = 3.6 ]; then coverage run setup.py nosetests; fi
  - if [ $python = 3.5 ]; then nosetests --verbose -exe microtc; fi

after_success:
  - if [ $python = 3.6 ]; then coveralls || echo "Coveralls upload failed"; fi
  - if [ $TRAVIS_BRANCH = "master" -a $python = 3.6 ]; then python setup.py sdist; pip install twine; twine upload -u mgraffg -p $TWINE dist/*.tar.gz; fi
  - if [ $TRAVIS_BRANCH = "master" ]; then source deactivate; conda install --yes pip conda-build jinja2 anaconda-client; conda build conda-recipe --quiet; fi
  - python continuous-integration/move-conda-package.py conda-recipe  
  - which binstar
  - python continuous-integration/binstar-push.py

notifications:
    email:
      recipients:
        - mario.graff@infotec.mx
        - eric.tellez@infotec.mx
        - sabino.miranda@infotec.mx
        - dmoctezuma@centrogeo.edu.mx
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always






language: python
python:
  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod 755 miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - pip install coverage
  - pip install coveralls
  - pip install numpy
  - pip install scipy 
  - pip install scikit-learn
  - pip install gensim
  - pip install nose

script: nosetests --with-coverage --cover-package=microtc

after_success: coveralls || echo "Coveralls upload failed"

notifications:
    email:
      recipients:
        - mario.graff@infotec.mx
        - eric.tellez@infotec.mx
        - sabino.miranda@infotec.mx
        - dmoctezuma@centrogeo.edu.mx

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
